version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14268:14268"
      - "16686:16686"
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
